In [41]:
import numpy as np
import math

In [42]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [43]:
import time
import sys

In [44]:
l = range(1000)
print(sys.getsizeof(5)*len(l))
array = np.arange(1000)
print(array.size*array.itemsize)

28000
4000


In [45]:
a =np.array([[2,4],[6,7]])
print(a)
print(a.ndim)
print(a.itemsize)

[[2 4]
 [6 7]]
2
4


In [46]:
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [48]:
np.arange(1,5)

array([1, 2, 3, 4])

In [49]:
np.arange(1,5,2)

array([1, 3])

In [50]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [51]:
a = np.array([[1,2],[3,6],[6,7]])
a

array([[1, 2],
       [3, 6],
       [6, 7]])

In [52]:
a.shape

(3, 2)

In [53]:
a.reshape(2,3)

array([[1, 2, 3],
       [6, 6, 7]])

In [54]:
a.ravel()

array([1, 2, 3, 6, 6, 7])

In [55]:
a

array([[1, 2],
       [3, 6],
       [6, 7]])

In [56]:
 a.max()

7

In [57]:
a.sum(axis = 0)

array([10, 15])

In [58]:
a.sum(axis = 1)

array([ 3,  9, 13])

In [60]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.44948974],
       [2.44948974, 2.64575131]])

In [63]:
np.std(a)

2.266911751455907

In [64]:
a = np.array([[1,2],[3,5]])
b= np.array([[3,7], [5,7]])
print(a)
print(b)

[[1 2]
 [3 5]]
[[3 7]
 [5 7]]


In [65]:
a+b

array([[ 4,  9],
       [ 8, 12]])

In [66]:
a.dot(b)

array([[13, 21],
       [34, 56]])

In [67]:
n = [4,6,5,6,7,8,8]
n[1:5]

[6, 5, 6, 7]

In [69]:
n[:-1]

[4, 6, 5, 6, 7, 8]

In [73]:
a

array([[1, 2],
       [3, 5]])

In [75]:
a[1,1]

5

In [76]:
a[0,0]

1

In [77]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [79]:
print(a,b)

[[0 1]
 [2 3]
 [4 5]] [[ 6  7]
 [ 8  9]
 [10 11]]


In [81]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [82]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [83]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [84]:
b  = a > 4
b

array([[False, False, False, False, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True]])

In [85]:
x = np.array([[1,2,3],
             [4,6,5],
              [5,7,6]], np.int32)
np.savetxt("test.txt", x)

In [86]:
y = np.loadtxt("test.txt")
print(y)

[[1. 2. 3.]
 [4. 6. 5.]
 [5. 7. 6.]]


In [87]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
for i in a:
    for cell in i:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
